FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    git \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements-lite.txt ./
RUN pip install --no-cache-dir -r requirements-lite.txt

COPY . /app

CMD ["python", "bot.py"]
